service: xteam-tgl-br-bot

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    BOT_TOKEN: '5034754222:AAF9fiuUsWzS7xQHM2JKL0f4F4juLbxp-FU'

plugins:
  - serverless-plugin-typescript

functions:
  webhook:
    handler: functions/webhook.run
    events:
      - http:
          path: webhook
          method: post
          cors: true

  set-webhook:
    handler: functions/setWebHook.run
    events:
      - http:
          path: setWebhook
          method: post
          cors: true
